name: Test setting environment
on: 
  push:
    tags:
      - 'env-*'

jobs:
  package:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      PACKAGECLOUD_REPOSITORY: test
    steps:
      - name: Configure target repository
        # If the ref name includes -test then go to the dev repo, else to test.
        run: |
          if [[ "$GITHUB_REF_NAME" =~ "-test" ]]; then
             echo "PACKAGECLOUD_REPOSITORY=dev" >> $GITHUB_ENV; 
          fi
      - name: Document target repository
        run: |
          echo "Cloud repo: $PACKAGECLOUD_REPOSITORY"
      - uses: docker://alpine:latest
        with:
          entrypoint: /usr/bin/env
          repo: ${{ env.PACKAGECLOUD_REPOSITORY }}
