name: Upload snap to packagecloud.io
on: 
  push:
    branches: 
    - '[a-z]*'

jobs:
  package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: '[push event] Dump some info'
        run: |
          echo push branch event
          echo GITHUB env
          env | grep GITHUB
          echo ===========================================
          echo git branch
          git branch
          git 
          if [[ "$GITHUB_REF_NAME" =~ "-test" ]]; then
             echo "PACKAGECLOUD_REPOSITORY=dev" >> $GITHUB_ENV; 
          fi
